-- 코드를 작성해주세요
WITH RECURSIVE COLONY AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, GEN + 1 AS GEN
    FROM ECOLI_DATA E JOIN COLONY C ON E.PARENT_ID = C.ID
)

SELECT ID
FROM COLONY
WHERE GEN = 3