WITH RECURSIVE cnt AS(
    SELECT 1 AS ID, 0 AS CHILD_COUNT
    UNION ALL
    SELECT ID+1 AS ID, 0 AS CHILD_COUNT
    FROM cnt
    WHERE ID < (SELECT COUNT(*) FROM ECOLI_DATA)
), AA AS(
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL
)

SELECT B.ID, CASE WHEN A.CHILD_COUNT IS NULL THEN 0 ELSE A.CHILD_COUNT END AS CHILD_COUNT
FROM AA A RIGHT JOIN cnt B ON A.PARENT_ID = B.ID;