-- 코드를 입력하세요
WITH RECURSIVE TMP AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM TMP
    WHERE HOUR<23
)

SELECT ROUND(HOUR) AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM (SELECT ROUND(HOUR(DATETIME)%24) AS HOUR, ANIMAL_ID FROM ANIMAL_OUTS 
      UNION ALL
      SELECT HOUR, NULL AS ANIMAL_ID FROM TMP) AS A
GROUP BY HOUR
ORDER BY HOUR;