-- 11월 내에 빌린 기록이 있는 데이터만 모아놓은 테이블
WITH RENT AS(
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
      AND END_DATE   >= '2022-11-01'
), FEES AS(
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
),OK AS(
    SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * 30 * (100-F.DISCOUNT_RATE) * 0.01) AS DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C LEFT JOIN FEES F ON C.CAR_TYPE = F.CAR_TYPE
    WHERE C.CAR_TYPE IN ('SUV', '세단')
    AND NOT EXISTS (
        SELECT 1 FROM RENT R
        WHERE R.CAR_ID = C.CAR_ID
    ) 
)

SELECT CAR_ID,
       CAR_TYPE,
       FLOOR(DAILY_FEE) AS FEE
FROM OK
WHERE DAILY_FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC