-- 코드를 입력하세요
SELECT a.PRODUCT_CODE AS PRODUCT_CODE, SUM(b.SALES_AMOUNT*a.PRICE) AS SALES
FROM PRODUCT a JOIN OFFLINE_SALE b ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY 1
ORDER BY SUM(b.SALES_AMOUNT*a.PRICE) DESC, a.PRODUCT_CODE;