-- 코드를 입력하세요
# SELECT *, SUM(SALES)
# FROM BOOK A JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID JOIN AUTHOR C ON A.AUTHOR_ID = C.AUTHOR_ID
# WHERE MONTH(B.SALES_DATE) = 1
# GROUP BY A.BOOK_ID;

SELECT A.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY, SUM(B.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK A JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID 
     JOIN AUTHOR C ON A.AUTHOR_ID = C.AUTHOR_ID
WHERE MONTH(B.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID , A.CATEGORY DESC;