WITH RECURSIVE CNT AS(
    SELECT FISH_TYPE, COUNT(FISH_TYPE) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

-- 코드를 작성해주세요
SELECT A.FISH_COUNT, B.FISH_NAME
FROM CNT A LEFT JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY A.FISH_COUNT DESC;