-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(a.SALES) AS TOTAL_SALES
FROM BOOK_SALES a JOIN BOOK b ON a.BOOK_ID = b.BOOK_ID
WHERE MONTH(SALES_DATE) = 1
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;

# SELECT *, SUM(SALES)
# FROM BOOK_SALES a JOIN BOOK b ON a.BOOK_ID = b.BOOK_ID
# WHERE MONTH(SALES_DATE) = 1
# GROUP BY b.CATEGORY;