-- 코드를 입력하세요
SELECT A.PRODUCT_ID, B.PRODUCT_NAME, SUM(A.AMOUNT*B.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER A JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE MONTH(A.PRODUCE_DATE) = 5 AND YEAR(A.PRODUCE_DATE) = 2022
GROUP BY B.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;