-- 코드를 입력하세요
SELECT B.HISTORY_ID, ROUND((DATEDIFF(B.END_DATE, B.START_DATE)+1)*A.DAILY_FEE*((100-C.DISCOUNT_RATE)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
     INNER JOIN CAR_RENTAL_COMPANY_CAR A 
     ON B.CAR_ID = A.CAR_ID AND A.CAR_TYPE = '트럭'
     INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
     ON C.CAR_TYPE = A.CAR_TYPE AND C.DURATION_TYPE = '7일 이상'
WHERE (DATEDIFF(B.END_DATE, B.START_DATE)+1) BETWEEN 7 AND 30
GROUP BY B.HISTORY_ID

UNION ALL

SELECT B.HISTORY_ID, ROUND((DATEDIFF(B.END_DATE, B.START_DATE)+1)*A.DAILY_FEE*((100-C.DISCOUNT_RATE)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
     INNER JOIN CAR_RENTAL_COMPANY_CAR A 
     ON B.CAR_ID = A.CAR_ID AND A.CAR_TYPE = '트럭'
     INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
     ON C.CAR_TYPE = A.CAR_TYPE AND C.DURATION_TYPE = '30일 이상'
WHERE (DATEDIFF(B.END_DATE, B.START_DATE)+1) BETWEEN 30 AND 90
GROUP BY B.HISTORY_ID

UNION ALL

SELECT B.HISTORY_ID, ROUND((DATEDIFF(B.END_DATE, B.START_DATE)+1)*A.DAILY_FEE*((100-C.DISCOUNT_RATE)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
     INNER JOIN CAR_RENTAL_COMPANY_CAR A 
     ON B.CAR_ID = A.CAR_ID AND A.CAR_TYPE = '트럭'
     INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
     ON C.CAR_TYPE = A.CAR_TYPE AND C.DURATION_TYPE = '90일 이상'
WHERE (DATEDIFF(B.END_DATE, B.START_DATE)+1) >= 90
GROUP BY B.HISTORY_ID

UNION ALL

SELECT B.HISTORY_ID, ROUND((DATEDIFF(B.END_DATE, B.START_DATE)+1)*A.DAILY_FEE) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
     INNER JOIN CAR_RENTAL_COMPANY_CAR A 
     ON B.CAR_ID = A.CAR_ID AND A.CAR_TYPE = '트럭'
WHERE (DATEDIFF(B.END_DATE, B.START_DATE)+1) BETWEEN 1 AND 7
GROUP BY B.HISTORY_ID

ORDER BY FEE DESC, HISTORY_ID DESC;