-- 코드를 입력하세요
SELECT b.TITLE, a.BOARD_ID, a.REPLY_ID, a.WRITER_ID, a.CONTENTS, DATE_FORMAT(a.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_REPLY AS a, USED_GOODS_BOARD AS b
WHERE b.CREATED_DATE
LIKE '%2022-10%' AND a.BOARD_ID = b.BOARD_ID
ORDER BY a.CREATED_DATE ASC, b.TITLE ASC ;
