-- 시간대별 재귀로 테이블 만듦: HOUR
-- 시간대별 입양 건수: ADOPTS
WITH RECURSIVE HOURS AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM HOURS WHERE HOUR<23
), ADOPTS AS(
    SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)
SELECT H.HOUR, IFNULL(A.COUNT, 0) AS COUNT
FROM HOURS H LEFT JOIN ADOPTS A ON H.HOUR = A.HOUR