-- 코드를 작성해주세요
WITH FRONT AS (
    SELECT SUM(CODE) AS 'SUMCODE'
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT SUMCODE FROM FRONT)
ORDER BY ID;