WITH POWER AS (
    SELECT COUNT(A.MEMBER_ID) AS CNT, A.MEMBER_ID, B.MEMBER_NAME
    FROM REST_REVIEW A LEFT JOIN MEMBER_PROFILE B ON A.MEMBER_ID = B.MEMBER_ID
    GROUP BY A.MEMBER_ID
    ORDER BY CNT DESC LIMIT 1
)

SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT( A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW A JOIN POWER B ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY A.REVIEW_DATE, A.REVIEW_TEXT;

