WITH TMP AS(
    SELECT DISTINCT A.ITEM_ID
    FROM ITEM_TREE A JOIN ITEM_INFO B ON B.ITEM_ID = A.PARENT_ITEM_ID
    WHERE RARITY = 'RARE'
)

-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A JOIN TMP B ON A.ITEM_ID = B.ITEM_ID
ORDER BY A.ITEM_ID DESC;