-- 코드를 작성해주세요
WITH PARENTS AS(
    SELECT ID, SUM(GENOTYPE) AS PARENT_GENOTYPE
    FROM ECOLI_DATA
    GROUP BY ID
)
SELECT DISTINCT E.ID, E.GENOTYPE AS GENOTYPE, P.PARENT_GENOTYPE
FROM PARENTS P RIGHT JOIN ECOLI_DATA E ON P.ID = E.PARENT_ID
WHERE P.PARENT_GENOTYPE & E.GENOTYPE = P.PARENT_GENOTYPE
ORDER BY E.ID