-- 코드를 입력하세요
SELECT C.APNT_NO, A.PT_NAME, C.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM APPOINTMENT C LEFT JOIN PATIENT A ON C.PT_NO = A.PT_NO LEFT JOIN DOCTOR B ON B.DR_ID = C.MDDR_ID
WHERE C.APNT_CNCL_YN LIKE 'N' AND DATE_FORMAT(C.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND C.MCDP_CD LIKE 'CS'
ORDER BY C.APNT_YMD;