-- 코드를 작성해주세요
WITH CNT AS(
SELECT COUNT(B.FISH_NAME) AS FISH_CNT
FROM FISH_INFO A LEFT JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE FISH_NAME = "BASS" OR FISH_NAME = "SNAPPER"
GROUP BY B.FISH_NAME)

SELECT SUM(FISH_CNT) AS FISH_COUNT
FROM CNT;