-- 코드를 작성해주세요
SELECT C.ID, F.FISH_NAME, F.LENGTH
FROM (FISH_INFO C JOIN FISH_NAME_INFO D ON C.FISH_TYPE = D.FISH_TYPE) JOIN (SELECT MAX(A.LENGTH) AS LENGTH, B.FISH_NAME
FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_NAME) F ON C.LENGTH = F.LENGTH AND D.FISH_NAME = F.FISH_NAME;