-- 코드를 입력하세요
WITH TMP AS(
    SELECT YEAR(JOINED) AS YEAR ,COUNT(DISTINCT USER_ID)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS , ROUND(COUNT(DISTINCT B.USER_ID)/ 
                                                                                                                     (SELECT COUNT(DISTINCT USER_ID)
                                  FROM USER_INFO
                                  WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE A LEFT OUTER JOIN USER_INFO B ON A.USER_ID = B.USER_ID 
WHERE YEAR(B.JOINED) = 2021
GROUP BY YEAR, MONTH;